### ISSUE TITLE
Migrations error out on Rails 4

### ISSUE THREAD

**Issue by shayneoAtNorwood** [richpeck/exception_handler#46] opened 2017-03-20 08:07 UTC
`ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base
`

When I set db: true and attempt a rake db:migrate it fails out with the above error. I've looked at the migration in the library and the syntax is pretty alien. Maybe its a rails 5 thing? Needless to say, it doesn't seem to work.

Is there a work around? I cant upgrade to rails 5 as its a rather huge existing codebase, but perhaps a regular rails 4 style migration migiht fix it?

**Comment by richpeck** [comment] 2017-03-20 09:16
Hmm. let me have a little look at this - will reply in perhaps an hour or so (just in the middle of something).

**Comment by richpeck** [comment] 2017-03-20 12:13
Okay so the error is not caused by the migration but the way in which the db table is [tested on init](https://github.com/richpeck/exception_handler/blob/master/lib/exception_handler/config.rb#L85):

`raise ExceptionHandler::Error, "Migration Required → \"#{db}\" doesn't exist" if @db && !ActiveRecord::Base.connection.table_exists?(db)`

The issue is that since ActiveRecord is not loaded at this time, your error will appear (as it's considered fatal). The way to resolve is to remove this, OR make it load after ActiveRecord.

I have done the latter (for now) and pushed the update to [`0.7.6.0`](https://rubygems.org/gems/exception_handler/versions/0.7.6.0). You'll get an error saying that you need to perform a migration - where inputting `rails db:migrate` should sort it out for you.

**Comment by richpeck** [comment] 2017-03-20 12:13
If you let me know if this works, I'll close the issue, otherwise we should work to get it fixed

**Closed** 2017-04-04 18:27 UTC
